  language: go
  go:
    - 1.7
    
  install:
    # Add Godeps dependencies to GOPATH and PATH
    - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
    - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

  script:
- go get -u github.com/gorilla/handlers
- go test -cover -v
